### ISSUE TITLE
(PY-D0002) Missing class docstring

### ISSUE THREAD

**Issue by ZigRazor** [ZigRazor/PyStateMachine#22]
## Description
Class docstring is missing. If you want to ignore this, you can configure this in the `.deepsource.toml` file. Please refer to [docs](https://deepsource.io/docs/analyzer/python.html#skip-doc-coverage) for available options.

## Occurrences
There are 8 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/ZigRazor/PyStateMachine/issue/PY-D0002/occurrences/](https://deepsource.io/gh/ZigRazor/PyStateMachine/issue/PY-D0002/occurrences/)

**Comment by afro-coder** [comment]
Hey I was wondering if I just have to add the docstring after trying to understand the code or do I have to add something pre-defined

**Comment by ZigRazor** [comment]
Just add the docstring
