### ISSUE TITLE
(FLK-E501) Line too long

### ISSUE THREAD

**Issue by ZigRazor** [ZigRazor/PyStateMachine#38]
## Description
Line length greater than configured `max_line_length` detected, defaults to 79 character. This limit can be configured [docs](https://deepsource.io/docs/analyzers/python.html#max-line-length)

## Occurrences
There are 8 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/ZigRazor/PyStateMachine/issue/FLK-E501/occurrences/](https://deepsource.io/gh/ZigRazor/PyStateMachine/issue/FLK-E501/occurrences/)

**Comment by Areadrill** [comment]
Hi! I'd love to take this issue

**Comment by ZigRazor** [comment]
Ok @Areadrill

**Comment by Areadrill** [comment]
Quick question: The link for the lint configs is broken. Do you want me to try to shorten the lines, or would you prefer to increase the maximum?

**Comment by ZigRazor** [comment]
Shorten the lines please
