### ISSUE TITLE
(FLK-E265) Block comment should start with `#`

### ISSUE THREAD

**Issue by ZigRazor** [ZigRazor/PyStateMachine#39]
## Description
Block comments should have one space before the pound sign `#` and the comment itself.

## Occurrences
There are 9 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/ZigRazor/PyStateMachine/issue/FLK-E265/occurrences/](https://deepsource.io/gh/ZigRazor/PyStateMachine/issue/FLK-E265/occurrences/)

**Comment by Areadrill** [comment]
Hi! I can also take this one, since I'll be sifting through the code

**Comment by DantrazTrev** [comment]
Hei @ZigRazor I would like to take up this issue

**Comment by DantrazTrev** [comment]
> Hi! I can also take this one, since I'll be sifting through the code

I apologize @Areadrill I didn't your comment you can take this up

**Comment by Areadrill** [comment]
Nah all good. There's plenty of issues to go around

**Comment by DantrazTrev** [comment]
> Nah all good. There's plenty of issues to go around

Thanks 😅
