### ISSUE TITLE
Write a good README to use the Framework

### ISSUE THREAD

**Issue by ZigRazor** [ZigRazor/PyStateMachine#4]
Please complete README to give the possibility to use the Framework in the right way

**Comment by karishmashuklaa** [comment]
@ZigRazor Hey, I'd like to work on this. Is there anything specific you want in the README?

**Comment by ZigRazor** [comment]
Hi @karishmashuklaa, 
the best things is a good "How to Run" with a small example of code, with an helpful comment in each line to explain the snippets of code. 
Then there is the "Example" Section to write, with the command to run the single example. ( would be useful also another README under the "sample" folder. )
After this also the "Test Suite" Section is important, in this section i need only the description of how to run tests. ( would be useful also another README under the "tests" folder. )
It would be not bad, also a more verbose introduction, with some images.
If you have other dubts do not hesitate to write me back.


Thank you in advance

**Comment by ZigRazor** [comment]
I Assign this Issue to you

**Comment by karishmashuklaa** [comment]
@ZigRazor I will get started with it soon and let you know if I have any doubts 🎉

**Comment by youChipS** [comment]
Is this issue still available?

**Comment by ZigRazor** [comment]
yes, I assign it to you!

**Comment by youChipS** [comment]
Hi,

If my pull request is suitable please accept.

I can make quick updates today if necessary.

Thanks,
Shaun
